// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

<<<<<<< HEAD
import * as $City_City_ from "./routes/City/[City].tsx";
import * as $Country_country_ from "./routes/Country/[country].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
=======
import * as $City_index from "./routes/City/index.tsx";
import * as $Country_country_ from "./routes/Country/[country].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
>>>>>>> c28cad1bcec1ff5d77a4175e2f60e74410e12c32
import * as $search_index from "./routes/search/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
<<<<<<< HEAD
    "./routes/City/[City].tsx": $City_City_,
    "./routes/Country/[country].tsx": $Country_country_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
=======
    "./routes/City/index.tsx": $City_index,
    "./routes/Country/[country].tsx": $Country_country_,
    "./routes/_404.tsx": $_404,
    "./routes/greet/[name].tsx": $greet_name_,
>>>>>>> c28cad1bcec1ff5d77a4175e2f60e74410e12c32
    "./routes/search/index.tsx": $search_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
