// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $AllBreeds from "./routes/AllBreeds.tsx";
import * as $BreedSearch from "./routes/BreedSearch.tsx";
import * as $Breed_Image_Image_ from "./routes/Breed/Image/[Image].tsx";
import * as $Breed_breed_ from "./routes/Breed/[breed].tsx";
import * as $RandomImage from "./routes/RandomImage.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $InputSearchBreed from "./islands/InputSearchBreed.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/AllBreeds.tsx": $AllBreeds,
    "./routes/BreedSearch.tsx": $BreedSearch,
    "./routes/Breed/Image/[Image].tsx": $Breed_Image_Image_,
    "./routes/Breed/[breed].tsx": $Breed_breed_,
    "./routes/RandomImage.tsx": $RandomImage,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/InputSearchBreed.tsx": $InputSearchBreed,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
